all:
  site:
    script_version: 2

  sendmail:
      host: smtp.station.cz
      port: 587
      username: developer.vychodoceskahypoteka.cz
      password: vyN3ETnwkFLc

  emails:
    lead: [vitekt@email.cz]

  cache:
      type: <?php echo $_SERVER['HTTP_HOST'] == 'www.vychodoceskahypoteka.cz' ? 'xcache' : 'apc' ?>

dev:
  emails:
    lead: [vitekt@email.cz]
