<?php

/**
 * BaseLead
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property integer $amount
 * @property string $name
 * @property string $contact
 * 
 * @method string  getType()    Returns the current record's "type" value
 * @method integer getAmount()  Returns the current record's "amount" value
 * @method string  getName()    Returns the current record's "name" value
 * @method string  getContact() Returns the current record's "contact" value
 * @method Lead    setType()    Sets the current record's "type" value
 * @method Lead    setAmount()  Sets the current record's "amount" value
 * @method Lead    setName()    Sets the current record's "name" value
 * @method Lead    setContact() Sets the current record's "contact" value
 * 
 * @package    vychodoceskahypoteka.cz
 * @subpackage model
 * @author     vychodoceskahypoteka.cz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLead extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lead');
        $this->hasColumn('type', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('contact', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}