<?php

/**
 * LeadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lead');
    }
}