<?php

/**
 * Lead
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Lead extends BaseLead
{
    const TYPE_BUY = 'kupuji-nemovitost';
    const TYPE_REFINANCE = 'refinancuji-hypoteku';

}
